sudo: required
services:
    - docker

before_install:
    - docker build -t prasannacn/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run prasannacn/react-test npm test -- --coverage

after_success:
    - docker build -t react-client ./client
    - docker build -t react-nginx ./nginx
    - docker build -t react-server ./server
    - docker build -t react-worker ./worker
    #log in docker CLI
    - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
    # push image to docker hub
    - docker tag react-client prasannacn/react-client:1.0
    - docker tag react-nginx prasannacn/react-nginx:1.0
    - docker tag react-server prasannacn/react-server:1.0
    - docker tag react-worker prasannacn/react-worker:1.0
    - docker push prasannacn/react-client:1.0
    - docker push prasannacn/react-nginx:1.0
    - docker push prasannacn/react-server:1.0
    - docker push prasannacn/react-worker:1.0