sudo: required
services:
    - docker

before_install:
    - docker build -t prasannacn/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run prasannacn/react-test npm test -- --coverage

after_success:
    - docker build -t prasannacn/react-client:1.0 ./client
    - docker build -t prasannacn/react-nginx:1.0 ./nginx
    - docker build -t prasannacn/react-server:1.0 ./server
    - docker build -t prasannacn/react-worker:1.0 ./worker
    #log in docker CLI
    - echo "$Docker_Pass" | docker login docker.io -u "$Docker_ID" --password-stdin
    # push image to docker hub
    - docker push prasannacn/react-client:1.0
    - docker push prasannacn/react-nginx:1.0
    - docker push prasannacn/react-server:1.0
    - docker push prasannacn/react-worker:1.0